pipeline {
    agent none

    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-u 0:0 --mount type=bind,source="/var/lib/jenkins/.m2",target="/root/.m2"'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
                sh 'mvn test'
                sh './jenkins/scripts/deliver.sh'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Container') {
            agent any
            steps {
                sh 'docker ps -a'
            }
        }
    }
}