pipeline {
    agent none

    options {
        skipStagesAfterUnstable()
    }

    parameters {
        string(name: 'ImageName', defaultValue: 'simple-java-maven')
        string(name: 'RepoName', defaultValue: 'ext90021')
    }
    stages {
        stage('Build and Test') {
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-u 0:0 --mount type=bind,source="/var/lib/jenkins/.m2",target="/root/.m2"'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
                sh 'mvn test'
                sh './jenkins/scripts/deliver.sh'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Compile Docker image') {
            agent any
            steps {
                sh "cp ./target/my-app-1.0-SNAPSHOT.jar ./docker"
                sh "/usr/bin/docker build -t ${params.ImageName}:${BUILD_ID} ./docker"
            }
        }

        stage('Push Docker image') {
            agent any
            steps {
                sh "/usr/bin/docker tag ${params.ImageName}:${BUILD_ID} ${params.RepoName}/${params.ImageName}:${BUILD_ID}"
                sh "/usr/bin/docker push ${params.RepoName}/${params.ImageName}:${BUILD_ID}"
            }
        }
        stage('Deploy') {
            agent any
            steps {
                sh "/usr/bin/docker run ${params.RepoName}/${params.ImageName}:${BUILD_ID}"
            }
        }
    }
}