pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-u 0:0 --mount type=bind,source="/var/lib/jenkins/.m2",target="/root/.m2"'
        }
    }

    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Build Container') {
            agent any
            steps {
                sh 'cp target/my-app-1.0-SNAPSHOT.jar .'
                sh 'docker build -t myapp .'
            }
        }
        stage('Test Container') {
            agent any
            steps {
                sh 'docker run myapp'
            }
        }

    }
}